---
title: "Figure drafts for Jan 2017 submission"
author: "Eric Kernfeld"
date: "January 18, 2017"
output: html_document
---

####Setup 

```{r}
results_path = Sys.getenv( "FREEZR_DESTINATION" )

# # Retrieve Seurat obj with tSNE redone 
path_to_Seurat_obj = inventory_get( tag = "overview_clean_labeled" )
dge = readRDS( path_to_Seurat_obj )
dge@raw.data   %<>% Matrix(sparse = T)
dge@data       %<>% Matrix(sparse = T)
dge@scale.data = NULL
gc()

```

#### Cluster markers

```{r}
# # Find markers for individual clusters
main_types = levels(dge@ident)
de_genes = as.list( main_types ); names(de_genes) = main_types
for( ct in main_types ){
  de_genes[[ct]] = FindMarkersFlex( dge, ident.use = "ident", ident.1 = ct, thresh.use = 0.5 )
  de_genes[[ct]]$cluster = ct
}
de_genes = Reduce( x = de_genes, f = rbind )
dir.create.nice( results_path )
write.table( de_genes %>% tidy_marker_table, 
             file.path( results_path, "all_genes_tested_detailed.txt" ),
             sep = "\t", quote = F, col.names = T, row.names = F ) 
write.table( de_genes %>% subset( q.value < 0.01 ) %>% tidy_marker_table, 
             file.path( results_path, "all_genes_tested_detailed_fdr_0_01.txt" ),
             sep = "\t", quote = F, col.names = T, row.names = F ) 

freezr::inventory_add( inv_location = today_dest, 
                       tag = "all_genes_tested_fine", force = T,
                       parent_tag = "overview_clean_labeled",
                       filename = file.path( results_path, "all_genes_tested_detailed.txt" ), 
                       extra = "Markers for figure 1 individual clusters" )

```

#### Merged cluster markers

```{r}

# # Find broader markers 
larger_sets = list( BLD123 = paste0("BLD", 1:3),
                    TEC_all = paste0("TEC", 1:3),
                    BLD_all = paste0("BLD", 1:5) )

de_genes = larger_sets; names(larger_sets) = names(larger_sets)
for( ct in names(larger_sets) ){
  de_genes[[ct]] = FindMarkersFlex( dge, ident.use = "ident", ident.1 = larger_sets[[ct]], thresh.use = 0.5 )
  de_genes[[ct]]$cluster = ct
}



de_genes = Reduce( x = de_genes, f = rbind )
dir.create.nice( results_path )
write.table( de_genes, file.path( results_path, "all_genes_tested_coarse.txt" ),
             sep = "\t", quote = F, col.names = T, row.names = F ) 

freezr::inventory_add( inv_location = today_dest, 
                       tag = "all_genes_tested_coarse", force = T,
                       parent_tag = "overview_clean_labeled",
                       filename = file.path( results_path, "all_genes_tested_coarse.txt" ), 
                       extra = "Markers for figure 1 TECs, blood, and T-cells. " )
```
