---
title: "Figure drafts for Jan 2017 submission"
author: "Eric Kernfeld"
date: "January 18, 2017"
output: html_document
---

#### Setup

Get data; set up colors as in overview tSNE

```{r}
results_path = Sys.getenv( "FREEZR_DESTINATION" )  

# # Retrieve Seurat obj and plot thymus makeup over time
dge = freezr::inventory_get( tag = "overview_clean_labeled" ) %>% readRDS

# # Generate dendrogram for paper
{
  pdf(file.path(results_path, "cluster_dendrogram.pdf"))
  dge %<>% BuildClusterTree
  dev.off()
}

cell_types = smaller_types = levels(dge@ident)
```

#### GO heatmap 

```{r, eval = FALSE}

# # Retrieve stats on genes and clusters
de_genes_fine = read.table( freezr::inventory_get( tag = "all_genes_tested_fine" ),
                       header = T, stringsAsFactors = F )
de_genes_coarse = read.table( freezr::inventory_get( tag = "all_genes_tested_coarse" ),
                              header = T, stringsAsFactors = F )
de_genes_coarse$cluster[de_genes_coarse$cluster == "BLD_most"] = "BLD123"
de_genes = rbind( de_genes_fine, de_genes_coarse )
positive_markers = as.list(smaller_types)
names(positive_markers) = smaller_types
for( ct in cell_types ){
  positive_markers[[ct]] = subset( de_genes, cluster == ct & q.value < 0.01 & avg_diff > 1.5, select = "gene", drop = TRUE )
}
p = make_go_heatmap( cluster_markers = positive_markers, num_genes_tested = nrow(dge@data) )
p = p + theme(axis.text.x = element_text(angle = 90))
p = p + scale_fill_gradient( low = "white", high = "blue")
ggsave(file.path(results_path, "GO_heatmap_fc_filter_strict.pdf"), p, width = 11, height = 11)


for( ct in cell_types ){
  positive_markers[[ct]] = subset( de_genes, cluster == ct & q.value < 0.01 & avg_diff > 0, select = "gene", drop = TRUE )
}
p = make_go_heatmap( cluster_markers = positive_markers, num_genes_tested = nrow(dge@data) )
p = p + theme(axis.text.x = element_text(angle = 90))
p = p + scale_fill_gradient( low = "white", high = "blue")
ggsave(file.path(results_path, "GO_heatmap_fc_filter_lax.pdf"), p, width = 11, height = 11)

```

##### Data driven and handpicked together, cluster-resolution heatmap

```{r}
genes_handpicked = c("Actb", "Ptprc",
                      "Myb", "Cd3e","Cd44", 
                     "Il2ra", "Rag1", "Ptcra", 
                     "Cd8a", "TRA_plus_TRB",
                     "Klrb1c", "Klrd1", "Itgax", "Lyz2", 
                     "Il7", "Foxn1", "Prss16", "Psmb11",  "Aire", 
                     "Esam", "Egfl7",  "Col3a1", "Pdgfra", "Pdgfrb")

filtered_genes = rbind( de_genes_fine   %>% dplyr::top_n( 50, wt = avg_diff ), 
                        de_genes_coarse %>% dplyr::top_n( 50, wt = avg_diff ) )
filtered_genes = filtered_genes[order(filtered_genes$cluster), ]

# # Prepare to make heatmaps
gimme_subset = function(ct) { subset( de_genes, cluster == ct ) }

# # Small heatmap
genes_dd_short = smaller_types %>%
  lapply( FUN=gimme_subset ) %>%
  lapply( FUN = dplyr::top_n, n = 5, wt = avg_diff ) %>%
  Reduce( f=rbind ) %>%
  extract2("gene")

p_heat = make_heatmap_for_table( dge = dge,
                                 ident.use = "ident",
                                 genes_in_order = c(genes_dd_short, genes_handpicked) %>% unique,
                                 desired_cluster_order = smaller_types,
                                 aggregator = mean,
                                 norm_fun = standardize,
                                 labels = "all" ) 

p_heat$data$data_driven = "Curated"
p_heat$data$data_driven[p_heat$data$gene %in% genes_dd_short] = "Data driven"
p_heat$data$data_driven %<>% factor(levels = c( "Data driven", "Curated" ), ordered = T )
p_heat = p_heat + facet_grid(data_driven~., scales = "free", space = "free_y")
p_heat = p_heat + scale_fill_gradientn( colours = blue_gray_red )

ggsave( filename = file.path( results_path, "heatmap_cluster_mean.pdf"),
        plot = p_heat,
        width = 9, height = 9)


```


#### Large heatmap

```{r}
# Quantify expression by clusters (coarse and fine)
library(Matrix)
percent_expressing_fine   = aggregate_nice( t(dge@data), by = dge@ident,                  FUN = prop_nz ) %>% t
percent_expressing_coarse = aggregate_nice( t(dge@data), by = dge@data.info$simple_ident, FUN = prop_nz ) %>% t

# Isolate genes very specific to big or small clusters
get2 = function(x) sort(x, decreasing = T)[2]
pass_filter_idx_fine = 
  apply(percent_expressing_fine, 1, get2)*2 < 
  apply(percent_expressing_fine, 1, max)
pass_filter_idx_coarse = 
  apply(percent_expressing_coarse, 1, get2)*4 < 
  apply(percent_expressing_coarse, 1, max)
pct_geq_10 =  
  apply(percent_expressing_fine, 1, max) > 0.1
accepted = (pass_filter_idx_fine | pass_filter_idx_coarse) & pct_geq_10
markers_shown = which( accepted ) %>% names

# Assign cells to big clusters, then to small only if pct expressing has fc > 2 over next highest
clusters_fine   = apply(percent_expressing_fine,   1, function(x) names(which.max(x)))
clusters_coarse = apply(percent_expressing_coarse, 1, function(x) names(which.max(x)))
clusters_coarse = c("BLD" = "C1_5", "MES" = "C10", "END" = "C9", "TEC" = "C6_8")[clusters_coarse]
clusters_all= clusters_coarse
clusters_all[pass_filter_idx_fine] = clusters_fine[pass_filter_idx_fine]
names(clusters_all) = names(clusters_coarse) = names(clusters_fine)

# Relevel clusters to show blood and TEC overall next to their respective subclusters
clusters_all %<>% 
  factor( levels = c( "C1_5", cell_types[-c(9,10)], "C6_8", cell_types[c(9,10)] ), ordered = T ) 
assertthat::assert_that(clusters_all %>% table %>% equals(0) %>% any %>% not ) 

# Retain cluster assignments only for markers shown in heatmap
clusters_of_genes_shown = data.frame( gene = markers_shown, cluster = clusters_all[markers_shown] )
clusters_of_genes_shown = clusters_of_genes_shown[order(clusters_of_genes_shown$cluster), ]

# Save marker lists by cluster and also annotation results
write.table( clusters_of_genes_shown, 
             file.path( results_path, "genes_by_cluster_as_shown_in_huge_heatmap.txt" ),
             quote = F, row.names = F, col.names = T, sep = "\t" )
as_char_keep_nm = make_name_preserving(as.character)
genes_by_cluster = clusters_of_genes_shown %>% vectorize_preserving_rownames(i=2) %>% as_char_keep_nm %>% get_preimage
mapply( do_enrichr, geneset = genes_by_cluster, 
                    geneset_name = names(genes_by_cluster),
                    MoreArgs = list( results_path = results_path ) )


# Set row colorbar
rowSideColors = c( fig1_cols, 
                   "BLD" = "black", 
                   "C1_5" = "black",
                   "TEC" = "blue",
                   "C6_8" = "blue" )[clusters_of_genes_shown$cluster %>% as.character ]

# Order genes by cluster
p_colorbar = ggplot(data.frame(rowSideColors, index = seq_along(rowSideColors))) + 
  geom_tile(aes(x = 1, y = -index, fill = rowSideColors)) + 
  scale_fill_manual( values = setNames( unique( rowSideColors ), unique( rowSideColors ) ) )
p_colorbar = p_colorbar + theme(axis.line=element_blank(),
                                axis.ticks=element_blank(),
                                axis.text.x=element_blank(),
                                axis.text.y=element_blank(),
                                axis.title.x=element_blank(),
                                axis.title.y=element_blank(),
                                legend.position = "none")
ggsave(file.path(results_path, "full_colorbar.pdf"), p_colorbar, width = 2)

# Form test dataset and reorder levels of ident so columns come out ordered correctly
test_dge = dge %>% SubsetData(max.cells.per.ident = 20)
test_dge@ident %<>% factor( levels = cell_types, ordered = T )
dge@ident      %<>% factor( levels = cell_types, ordered = T )

quick_heatmap = function( test, col ){
  if( test ) {
    my_dge = test_dge
  } else {
    my_dge = dge
  }
  save_heatmap( dge = my_dge, 
                results_path = results_path, 
                genes.use = clusters_of_genes_shown$gene, 
                main = paste0( "heatmap_cellwise_test=", 
                               as.character( test ), 
                               "_col=", 
                               deparse( substitute( col ) ) ),
                ident.use = "ident",
                cluster_colors = fig1_cols,
                col = col, 
                rsc = rowSideColors[clusters_of_genes_shown$cluster %>% as.character] )
}

cols_yr = colorRampPalette( c( "khaki1", "orange", "red" ) )(50)
cols_bw = colorRampPalette( c( "black", "white"          ) )(50)
cols_wb = cols_bw %>% rev
cols_viridis = viridis::viridis( 50 )

# quick_heatmap( test = T, col = cols_wb )
# quick_heatmap( test = T, col = cols_bw )
# quick_heatmap( test = T, col = cols_viridis )
quick_heatmap( test = T, col = cols_yr )

# quick_heatmap( test = F, col = cols_wb )
# quick_heatmap( test = F, col = cols_bw )
# quick_heatmap( test = F, col = cols_viridis )
quick_heatmap( test = F, col = cols_yr )


```

##### Handpicked featureplots

```{r}
genes_handpicked = c("Actb", "Ptprc",
                      "Myb", "Cd3e","Cd44", 
                     "Il2ra", "Rag1", "Ptcra", 
                     "Cd8a", "TRA_plus_TRB",
                     "Zbtb16", "Klrd1", "Itgax", "Lyz2", 
                     "Il7", "Foxn1", "Prss16", "Psmb11",  "Aire", 
                     "Esam", "Egfl7",  "Col3a1", "Pdgfra", "Pdgfrb")
dge %<>% add_tcr
dge@raw.data = matrix()
dge@scale.data = matrix()
dge@data.info$TRA_plus_TRB = dge %>% FetchData(c("TRA_TOTAL", "TRB_TOTAL") ) %>% rowSums

quick_grid = function(idx, name) {
  save_plot_grid( dge, results_path, genes_handpicked[idx],
                name, ncol = 4, width = 8*4, height = 2*7, 
                leg_pos = c(0.0, 0.85),
                edit_fun = function( p ){
                  p = p + theme( plot.title = element_text( size = 30 ), 
                                 legend.title = element_text( size=30 ),
                                 legend.key.size =  unit( 0.3, "in" ), 
                                 legend.text = element_text( size=24 ) )  
                  return(p)
                },
                cols.use = c("khaki1", "red") )
}

quick_grid(1:8, "genes_fig1_yr_1")
quick_grid(8 + 1:8, "genes_fig1_yr_2")
quick_grid(16 + 1:8, "genes_fig1_yr_3")

save_plot_grid( dge, results_path, "Actb",
                "Actb", ncol = 4, width = 8, height = 7, 
                leg_pos = c(0.0, 0.85),
                edit_fun = function( p ){
                  p = p + theme( plot.title = element_text( size = 30 ), 
                                 legend.title = element_text( size=30 ),
                                 legend.key.size =  unit( 0.3, "in" ), 
                                 legend.text = element_text( size=24 ) )  
                  return(p)
                },
                cols.use = c("khaki1", "red") )
```
