---
title: "Figure drafts for Jan 2017 submission"
author: "Eric Kernfeld"
date: "January 18, 2017"
output: html_document
---

####Setup

Get data; set up colors as in overview tSNE

```{r}
results_path = Sys.getenv( "FREEZR_DESTINATION" )  


# # Retrieve Seurat obj and plot thymus makeup over time
dge = freezr::inventory_get( tag = "overview_clean_labeled" ) %>% readRDS

# # Generate dendrogram for paper
{
  pdf(file.path(results_path, "cluster_dendrogram.pdf"))
  dge = BuildClusterTree(dge)
  dev.off()
}

smaller_types = extract_tip_order(dge@cluster.tree[[1]])

```


##### Handpicked

```{r}
genes_handpicked = c("Actb", "Ptprc",
                     "Myb", "Cd3e", "Rag1", "Cd8a","Klrb1c", "Klrd1", "Itgax", "Lyz2", 
                     "Il7", "Foxn1", "Prss16", "Psmb11", 
                     "Aire", 
                     "Esam", "Egfl7",  "Col3a1", "Pdgfra", "Pdgfrb")
p_heat = make_heatmap_for_table( dge = dge,
                                 ident.use = "ident",
                                 genes_in_order = genes_fig2,
                                 desired_cluster_order = smaller_types,
                                 aggregator = mean,
                                 norm_fun = standardize,
                                 labels = "all" ) 
p_heat = p_heat + ggtitle("Top markers, average expression") + scale_fill_gradientn( colours = blue_gray_red )
ggsave( filename = file.path( results_path, "heatmap_fig2.pdf"),
        plot = p_heat,
        width = 9, height = 4)

save_plot_grid( dge, results_path, genes_handpicked, "genes_handpicked", ncol = 5, width = 32, height = 24 )

{
  pdf(file.path(results_path, "handpicked_heatmap_cellwise.pdf"))
  DoHeatmap( dge, genes.use = genes_handpicked )
  dev.off()
}

```

##### Data driven

```{r}

# # Retrieve stats on genes and clusters
de_genes = read.table( freezr::inventory_get( tag = "all_genes_tested_fine" ),
                       header = T, stringsAsFactors = F )
de_genes_coarse = read.table( freezr::inventory_get( tag = "all_genes_tested_coarse" ),
                              header = T, stringsAsFactors = F)
de_genes_coarse$cluster[de_genes_coarse$cluster == "BLD_most"] = "BLD123"
filtered_genes = rbind( de_genes        %>% subset( avg_diff > 1.5 ), 
                        de_genes_coarse %>% subset( avg_diff > 1.5 ) )
filtered_genes = filtered_genes[order(filtered_genes$cluster), ]


# # Prepare to make heatmaps
gimme_subset = function(ct) { subset( de_genes, cluster == ct ) }

# # Small heatmap
genes_dd_short = smaller_types %>%
  lapply( FUN=gimme_subset ) %>%
  lapply( FUN = top_n, n = 5, wt = avg_diff ) %>%
  Reduce( f=rbind ) %>% extract2("gene")

p_heat = make_heatmap_for_table( dge = dge,
                                 ident.use = "ident",
                                 genes_in_order = genes_dd_short,
                                 desired_cluster_order = smaller_types,
                                 aggregator = mean,
                                 norm_fun = standardize,
                                 labels = "all" ) 
p_heat = p_heat + ggtitle("Top markers, average expression") + scale_fill_gradientn( colours = blue_gray_red )
ggsave( filename = file.path( results_path, "heatmap_cluster_mean.pdf"),
        plot = p_heat,
        width = 9, height = 9)

{
  pdf(file.path(results_path, "data_driven_heatmap_cellwise.pdf"))
  DoHeatmap( dge, genes.use = genes_dd_short )
  dev.off()
}


```

