---
title: "Figure drafts for Jan 2017 submission"
author: "Eric Kernfeld"
date: "January 18, 2017"
output: html_document
---

#### Assemble data

```{r}
results_path = Sys.getenv( "FREEZR_DESTINATION" )

# Retrieve data; subset NKT cells
dge_atlas_NKT = inventory_get(tag = "overview_clean_labeled") %>% readRDS %>% 
  SubsetDataFlex( vars.use = "ident", predicate = "ident=='BLD5'")

# Add metadata and specially-aligned TCR counts. 
dge_atlas_NKT %<>% add_tcr
dge_atlas_NKT %<>% add_maehrlab_metadata("eday")
dge_atlas_NKT %<>% add_maehrlab_metadata("genotype")
dge_atlas_NKT@data.info$genotype[dge_atlas_NKT@data.info$genotype=="Pax9-Venus"] = "wt"
```

#### Redo exploration to get more resolution

```{r}
all_params = expand.grid( cc_method = c( "average" ),
                          excess_var_cutoff = c( 0.5, 0.8, 1.2 ),
                          log_expr_cutoff = c( 0.1 ), 
                          prop_genes_to_select = NA, 
                          num_genes_to_select = NA, 
                          var_gene_method = "seurat",
                          num_pc =  c(8, 12), 
                          clust_method = "SNN",
                          clust_granularities_as_string = "0.5",
                          plot_all_var_genes = F,
                          stringsAsFactors = F)
dge_atlas_NKT %<>% explore_embeddings(results_path=results_path, all_params = all_params )
```

