---
title: "Figure drafts for Jan 2017 submission"
author: "Eric Kernfeld"
date: "January 18, 2017"
output: html_document
---

#### Setup and initial exploration of TECs

```{r}
results_path = Sys.getenv( "FREEZR_DESTINATION" )

dge_rag1 = c( "Rag1null_E16_5_Epcam_rep1", 
              "Rag1KO_Epcam_rep2", 
              "Rag1KO_Epcam_rep3",
              "Rag1KO_WholeThy_rep1",
              "Rag1KO_WholeThy_rep2" ) %>%
  load_maehrlab_private_data %>% dge_merge_list %>% seuratify_thy_data( results_path )
dge_rag1 = add_maehrlab_metadata( dge_rag1, "eday" )

all_params = expand.grid( cc_method = c( "average" ),
                          excess_var_cutoff = c( 0.5 ),
                          log_expr_cutoff = c( 0.1 ), 
                          num_genes_to_select = NA, 
                          prop_genes_to_select = NA, 
                          var_gene_method = "seurat",
                          num_pc = c( 15 ), 
                          clust_method = "SNN",
                          clust_granularities_as_string = "0.5",
                          plot_all_var_genes = F,
                          stringsAsFactors = F )

dge_rag1 = knn_classifier( dge_train = inventory_get( tag = "overview_clean_labeled" ) %>% readRDS, 
                           dge_test = dge_rag1,
                           ident.use = "ident",
                           vars.all = NULL, my_transform = "PCA_20",
                           k = 25, reject_prop = 0.00 )
dge_rag1_TEC = dge_rag1 %>% SubsetDataFlex( vars.use = "classifier_ident", 
                                            predicate = "classifier_ident %in% paste0('TEC', 1:3)")
dge_rag1_TEC = explore_embeddings( dge_rag1_TEC, results_path = file.path( results_path, "Rag1null_TEC" ), all_params)
param_string = collapse_by_name(all_params[1, ])
inventory_add( tag = "dge_rag1_TEC",  filename = file.path( results_path, "Rag1null_TEC", param_string, "dge.data"), force = T )
dge_rag1_TEC %<>% add_maehrlab_metadata( "genotype" )
save_feature_plots( dge_rag1_TEC, results_path = file.path( results_path, "Rag1null_TEC" ),
                    gene_list_name = "overall_markers", types = c("pdf", "pdf_no_leg"),
                    cols.use = c("blue", "cadetblue3", "orange", "red", "purple"), 
                    gene_list = "orig.ident" ) 

```

#### TECs exploration with atlas

```{r}
dge_all = SeuratMerge( dge_rag1_TEC, 
                       inventory( tag = "whole_plus_sorted_16_labeled" ) %>% readRDS %>% 
                         SubsetDataFlex(vars.use = "eday", predicate = "eday==16.5") )
dge_all = explore_embeddings( dge_all, results_path = file.path( results_path, "all_TEC" ), 
                              test_mode = F, all_params)
dge_all %<>% add_maehrlab_metadata("genotype")
inventory_add( tag = "dge_rag1_TEC_plus_atlas",  filename = file.path( results_path, "all_TEC", param_string, "dge.data", force = T ))

save_feature_plots( dge_all, results_path = file.path( results_path, "all_TEC" ), 
                    gene_list = "genotype", gene_list_name = "genes_for_figures",
                    cols.use = c("Rag1null"="goldenrod", "wt"="cadetblue"), types = c("pdf", "pdf_no_leg"))

```


